- hosts: dev
  roles:
    - apt-update
    - bootstrap
    - ufw
    - nginx
    - node
    - david-www
  vars:
    node_env: development

- hosts: live
  roles:
    - apt-update
    - bootstrap
    - ufw
    - nginx
    - letsencrypt
    - node
    - david-www
    - david-www-letsencrypt
  vars:
    node_env: production
