- name: Ensure david-www group exists
  become: yes
  group: name={{service}} state=present

- name: Ensure david-www user exists
  become: yes
  user: name={{service}} comment="David" group={{service}}

- name: Copy Nginx config
  become: yes
  template: src=nginx.conf dest=/etc/nginx/conf.d/{{service}}.conf mode=0644 force=yes
  notify:
    - Restart Nginx

- name: Ensure Nginx is running
  become: yes
  service: name=nginx state=started

- name: Copy Upstart config
  become: yes
  template: src=upstart.conf dest=/etc/init/{{service}}.conf mode=0644 force=yes

- name: Clone david-www
  become: yes
  become_user: "{{service}}"
  git: dest=/home/{{service}}/{{service}} force=yes repo=https://github.com/{{repo}}.git version=master
  notify:
    - Restart {{service}}

- name: Copy app config
  become: yes
  copy: src=configs/{{node_env}}.json dest=/home/{{service}}/{{service}}/.davidrc owner={{service}} group={{service}} force=yes
  notify:
    - Restart {{service}}

- name: Install dependencies
  shell: NODE_ENV=production npm install --production  chdir=/home/{{service}}/{{service}}
  become: yes
  become_user: "{{service}}"

- name: Ensure the app is running
  become: yes
  service: name={{service}} state=started
