- name: Add certbot repository
  become: yes
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install certbot
  become: yes
  apt: name=python-certbot-nginx state=present

- name: Ensure the well-known webroot dir exists
  become: yes
  file: path=/var/www/well-known state=directory mode=0755 owner=www-data group=www-data
